name: Deploy Documentation

on:
  push:
    branches:
      - master
    # rebuild docs only on code changes
    paths:
        - 'packages/*/src/**'
        - '!packages/google-that/**'
  workflow_dispatch:

jobs:
  build-and-deploy-docs:
    name: Build and Deploy Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write


    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment

      - name: Build packages
        run: pnpm run build:packages

      - name: Build documentation
        run: pnpm run build:docs

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs