name: Mirror Repository

on:
  push:
    branches:
      - '**'

permissions:
  contents: read


jobs:
  sync:
    runs-on: ubuntu-latest
    # restrict to the main repository
    if: github.repository == 'typicalninja/google-sr'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Mirror
        uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'ssh://git@codeberg.org/typicalninja/google-sr.git'
          GIT_SSH_PRIVATE_KEY: ${{ secrets.MIRROR_GIT_SSH_PRIVATE_KEY }}
          #GIT_SSH_KNOWN_HOSTS: ${{ secrets.MIRROR_GIT_SSH_KNOWN_HOSTS }}
          # Known host seem not work
          # for now just skip verification
          # see here? https://github.com/yesolutions/mirror-action/issues/14
          GIT_SSH_NO_VERIFY_HOST: "true"