name: Publish Any Commit
permissions:
  contents: read

on:
  pull_request:
    # run only on code changes
    paths:
      - 'packages/*/src/**'
  push:
    branches:
      - '**'
    tags:
      - '!**'
    # pkg.pr.new only runs on code changes
    paths:
      - 'packages/*/src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

			- uses: ./.github/actions/setup-environment

      - name: Release commit-release
        run: pnpm dlx pkg-pr-new publish --compact --pnpm './packages/*' --no-template