name: Lint PR
on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  lint:
    name: Lint PR
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Setting up node v18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install workspace dependencies
        run: pnpm install --frozen-lockfile

      - name: Run lint
        run: pnpm exec biome check --no-errors-on-unmatched --files-ignore-unknown=true
