name: Run tests and collect coverage
permissions:
  contents: read
  
on:
  push:
    branches:
      - master
    # test only on code changes
    paths:
      - 'packages/*/src/**'
  schedule:
      - cron: "0 0 * * SUN"  # Run every 00:00 on Sunday
  workflow_dispatch:
  pull_request:
    # test only on code changes
    paths:
      - 'packages/*/src/**'


jobs:
  test:
    name: Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # setup pnpm to specific version to avoid breaking changes
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2
          run_install: false

      # action was tested on node 20.x
      - name: Install Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Package using tsup and turbo
        run: pnpm run build --filter=google-sr --filter=google-sr-selectors

      - name: Run tests
        run: pnpm run test --coverage

      - name: Upload results to Codecov
        # do not run on weekly schedule (only on pr and push)
        if: github.event_name != 'schedule'
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}